### ISSUE TITLE
Forge version does not match latest tag

### ISSUE THREAD

**Issue by esalberg** [jtopjian/puppet-sshkeys#15]
I ran into an issue where I needed to run "puppet module install jtopjian/sshkeys" for bootstrapping (I normally use r10k) and it installed the 1.0.0 version instead of 2.0.0.  These versions aren't very compatible.

Is there any way to update the Forge version to 2.0.0?

**Comment by jtopjian** [comment]
Yup - should be on the Forge now. Let me know if you have any issues.

**Comment by esalberg** [comment]
Looks good - thank you!
