### ISSUE TITLE
homedir / pubkey facts mount all automounted home directories

### ISSUE THREAD

**Issue by esalberg** [jtopjian/puppet-sshkeys#17]
We automount home directories for users depending on whether or not they're logged in to a server.  After implementing the module, we noticed that all home directories were being automounted regardless.  I'm pretty sure this is because of the ruby facts to collect all user home dirs and keys.

(As a side note, we have a central AD store for users, so they're not actually in the /etc/passwd file.  However, the Ruby etc library uses getent versus parsing the /etc/passwd file directly - in the latter case, I don't think we'd be having this issue.)

We don't actually care about getting the user home dirs / public keys as facts right now, but I can't see any way to gate whether or not to set that information other than removing the fact files, or even to restrict the facts to specific users (which would lower the impact at least).  Do you have any ideas?

**Comment by jtopjian** [comment]
Wow - this is a really interesting issue.

I'll modify the homedir fact to open and parse the passwd file rather than using ruby's native functionality. I'll let you know when this is done (sometime this evening, maybe) so you can test it out.

**Comment by esalberg** [comment]
Thank you so much!

I had been considering trying another module, but I'm very happy to stick with this one and test out the change. :)

**Comment by jtopjian** [comment]
Can you swap out `lib/facter/homedir.rb` with [this](https://gist.github.com/jtopjian/fb03d5ef74932010c7c0) and let me know if this resolves the issue? If so, I'll replace it in the module.

**Comment by esalberg** [comment]
The testing worked - I did need to copy your new fact code into the sshpubkey.rb fact as well (as I'm sure you already knew, but it was confusing me for a while, since the home directories looked right but the pubkeys were wrong).

This definitely resolves the biggest issue for us (mounting of the home directories).
-----------------------------

Ideally, I think what I'd really like - although this is probably more difficult - is a way to specify which users should have their homedirs and pubkeys fetched.  If I could do that, then using the original code would be fine (potentially better, as able to get ldap users' keys as well).

Another option would be to confine the fact based off another fact (i.e. whether or not to set the homedirs / pubkeys), but since it would be an arbitrary one, it would probably have to be an external fact, and thus the first time through, all the homedirs would get mounted (but they should time out, so that would be transient).

**Comment by jtopjian** [comment]
Oh, duh, actually I totally forgot about `sshpubkey.rb`. Sorry about that.

Let me think over your comments--they definitely have merit--and I'll get back to you.

**Comment by jtopjian** [comment]
OK, I think I have a solution -- let me know what you think :)

https://gist.github.com/jtopjian/fb03d5ef74932010c7c0

FYI: I'll be renaming `home_` to `homedir_` soon. `homedir_` was always my intention of the fact name, but somehow `home_` ended up getting used.

**Comment by esalberg** [comment]
I'll take a look right away - just finishing up the bit_length refactor. :)

**Comment by esalberg** [comment]
This works great!

I tested with both local users only (root, operator) and with an additional AD user.  The facts picked up the public keys and only mounted the home directories of the users listed in the new homedir_users fact.

Do you think you're going to have these merged into master this week?  Otherwise, I have a local fork of your module, and I can add these patches myself until you're ready.

**Comment by jtopjian** [comment]
Awesome :smile: 

I'll definitely be able to get this added to master, probably by Wednesday at the latest. I'll hold off on the home/homedir change until another time.

**Comment by jtopjian** [comment]
OK, changes have been committed. Can you verify everything works and I'll publish it to the Forge?

**Comment by esalberg** [comment]
Works for me!  Could you throw a new tag on it when you publish?  We try to freeze to a specific tag when moving modules to production.

Thanks for getting this all done so quickly - I really appreciate it.

**Comment by jtopjian** [comment]
Sorry for the delay. 2.1.0 should now be on the Forge. :)

**Comment by esalberg** [comment]
All set!  Thank you!
