### ISSUE TITLE
Using hyphens when collecting and exporting resources

### ISSUE THREAD

**Issue by tdotgreenshirt** [jtopjian/puppet-sshkeys#24]
Using the following to export user resources:

```
sshkeys::create_ssh_key { $user:
    create_ssh_dir => false,
}

  @@sshkeys::set_authorized_key { "svc-tsdocusign@${::hostname}":
    local_user  => 'svc-tsdocusign',
    remote_user => "${user}@${::fqdn}",
    tag         => "docusign-${::app_tier}"
  }
```

Notice that the local user I am using is svc-tsdocusign (with a hyphen). When collecting user resources:
`Sshkeys::Set_authorized_key <<| tag == "docusign-${::app_tier}" |>>`
I continue to receive the following:

> Notice: Public key from docusign@hostname.corp.host.internal (for local user svc-tsdocusign) not available yet. Skipping

When I use anything but a hyphen, such as an underscore (e.g svc_tsdocusign), the user is successfully collected. Why is the hyphen posing an issue?

**Comment by jtopjian** [comment]
@tdotgreenshirt That's a really good question.

To confirm, it is only the tag and the collection that are causing the problem? This will work?

```puppet
@@sshkeys::set_authorized_key { "svc-tsdocusign@${::hostname}":
  local_user  => 'svc-tsdocusign',
  remote_user => "${user}@${::fqdn}",
  tag         => "docusign_${::app_tier}"
}

Sshkeys::Set_authorized_key <<| tag == "docusign_${::app_tier}" |>>
```

**Comment by tdotgreenshirt** [comment]
@jtopjian That doesnt appear to be the issue. We use hundreds of exports and collections with hyphens and they all work as intended; however, the collection magically started working. I'll go ahead and resolve. Thanks

**Comment by jtopjian** [comment]
@tdotgreenshirt Well that's both strange and good 😄
