### ISSUE TITLE
set_authorized_key fails with puppet 6

### ISSUE THREAD

**Issue by whiphubley** [jtopjian/puppet-sshkeys#25]
When calling query_facts in set_authorized_key against puppetdb 6 I can see the connection on port 8081 with tcpdump but get the following error:

`Error while evaluating a Function Call, undefined method facts_query for #<PuppetDB::Parser:0x6bab009>`

Which seems to relate to the following code in the query_facts function:

`parser = PuppetDB::Parser.new
 query = parser.facts_query query, facts_for_query if query.is_a? String
 parser.facts_hash(puppetdb.query(:facts, query, :extract => [:certname, :name, :value]), facts)`

We use this module along with the dalen puppetdbquery module but something has broke since moving to puppet 6. We have updated both modules and am not aware of any other combination that can deploy ssh keys from puppetdb. Any help would be greatly appreciated.

**Comment by jtopjian** [comment]
Thank you for the heads-up.

I'll take a look at this when I can, but it might take a few weeks. All of my prod environments are still using versions earlier than 6, but I hope to begin looking at and updating things soon. No intention of this going stale since I also use this in prod 🙂

**Comment by whiphubley** [comment]
Thanks for the reply really appreciate it. Would really be great to get this working!

**Comment by jtopjian** [comment]
If you're able to find a solution, I'd be happy to incorporate it.

**Comment by whiphubley** [comment]
OK it seems all is well and that error is shown if the sshpubkey_username fact is not yet available in the puppetdb. Perhaps just handle the error with a cleaner message :-) Anyway thanks for the module it's great and helps us a lot. Keep up the good work.
